#!/bin/bash

##########################################################################################
# This script collects information about existing system for its compromise assessment.
# The logs generated by the script are useful for forensic investigations
##########################################################################################
echo "\033[31m ### Please install required packages like unhide, rkhunter, chkrootkit, clamav on the system before proceeding"

#if [ -f /etc/redhat-release ]; then
#	yum -y update
#	yum -y install epel-release
#	yum -y groupinstall 'Development Tools'
#	yum install -y wget git rkhunter unhide clamav chkrootkit
#else
#	apt-get -y update
#	apt-get -y install wget git build-essential rkhunter unhide clamav chkrootkit
#fi

echo "\033[31m ### Checking system resources ### \033[0m"

echo "\033[31m ### Checking OS Version ### \033[0m"
cat /etc/redhat-release

echo "\033[31m ### Checking cpu load and uptime ### \033[0m"
uptime

echo "\033[31m ### Check system memory usage ### \033[0m"
free -g

echo "\033[31m ### Checking system network rate use \033[0m"
sar -n DEV 3 1  | grep -vE '^$'

echo "\033[31m ### Checking system tools ### \033[0m"
ls -al `which stat` 
stat `which ps top netstat sshd lsof find`>/tmp/stats-systemtools.log
echo "/tmp/stats-systemtools.log"

echo "\033[31m ### Checking abnormal users ### \033[0m"
echo "\033[31m ### Checking password stat information, users with GID=0 or users with bash shell ### \033[0m"
stat /etc/passwd | grep -vE 'ile|Inode'
echo "\033[31m ### Checking users with GID=0 or users with bash shell ### \033[0m"
grep -E '/bash|:0+:' /etc/passwd | grep -vE 'root|mysql|rpm|mysql|shutdown|halt|sync'

echo "\033[31m ### Checking shadow stat information and no password user(s) ### \033[0m"
stat /etc/shadow | grep -vE 'ile|Inode'
echo "\033[31m ### Checking no password user(s) ### \033[0m"
awk -F: 'length($2)==0 {print $1}' /etc/shadow
echo ""

echo "\033[31m #### Checking service(s) and task(s) information ### \033[0m"
echo "\033[31m ### Checking chkconfig services ### \033[0m"
chkconfig --list |grep -E '2:on|3:on' | awk '{printf"%s ",$1}'
systemctl list-unit-files |grep -E '2:on|3:on' | awk '{printf"%s ",$1}'
sysv-rc-conf --list
echo ""
echo -e "\033[31m ### Checking  services in rc.local ### \033[0m"
grep -vE '^$|^#' /etc/rc.local
echo "\033[31m ### Checking crontab entries ### \033[0m"
crontab -l
ls -la /var/spool/cron/ >> /tmp/checkcrontab.log
ls -la /etc/cron* >> /tmp/checkcrontab.log
echo ""
echo "\033[31m ### Checking inetd services ### \033[0m"
cat /etc/inetd.conf | grep -v "^#"
echo "\033[31m ### Checking process information ### \033[0m"
echo "\033[31m ### Checking ps command results ### \033[0m"
ps axu | grep -v ]$
#echo "\033[31m ### Check hidden process ### \033[0m"
#ps -ef | awk '{print $2}' | sort -n | uniq >1
#ls /proc | sort -n |uniq >2
#diff 1 2 | awk '{printf"%s ",$0}'
echo ""

echo "\033[31m ### Checking network information ### \033[0m"
echo "\033[31m ### Checking network hosts configuration ### \033[0m"
cat /etc/hosts | grep -v 'localhost'
echo "\033[31m ### Checking dns (nameserver) details ### \033[0m"
cat /etc/resolv.conf | grep 'nameserver'
echo "\033[31m ### Checking ip details ### \033[0m"
/sbin/ip a|grep 'inet '| awk '{print $2}' | awk -F'/' '{printf"%s ",$1}'
echo ""
echo "\033[31m ### Checking if network interface is in promiscuous mode ### \033[0m"
ifconfig | grep 'PROMISC'
echo "\033[31m ### Checking if ip forwarding is enabled or not ### \033[0m"
cat /proc/sys/net/ipv4/ip_forward 
echo "\033[31m ### Checking rpc information ### \033[0m"
rpcinfo -p
echo "\033[31m ### Checking running network services information ### \033[0m"
netstat -nap | grep LISTEN
echo "\033[31m ### Checking process <-> port mapping ### \033[0m"
lsof -i > /tmp/checklsof
#cat /tmp/checklsof
echo ""

echo "\033[31m ### Checking files and module information ### \033[0m"
echo "\033[31m ### Checking files having link count(number) equals 0 ### \033[0m"
lsof +L1
echo "\033[31m ### Checking executable files that are changed in the last 3 days before now ### \033[0m"
find / -path "/proc" -prune -o -type f -executable -mtime -3 -print > /tmp/checkfilechange

echo "\033[31m ### Checking installed kernel modules ### \033[0m"
lsmod | awk '{printf"%s ",$1}'
echo ""


echo "\033[31m ### Checking ssh and bash settings ### \033[0m"
echo "\033[31m ### Checking ssh key login host ### \033[0m"
if [ -e /root/.ssh/authorized_keys ]; then
    awk '{printf"%s ",$3}' /root/.ssh/authorized_keys
fi
echo "\033[31m ### Checking ssh password login user ### \033[0m"
lastlog | grep -vE 'Never'
echo "\033[31m ### Checking logged in ssh users ### \033[0m"
w
echo "\033[31m ### Check ssh login success history ### \033[0m"
last -n 30
echo "\033[31m ### Check ssh login fail history ### \033[0m"
grep -ri "ail" /var/log/secure* | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'| sort -n | uniq | awk '{printf"%s ",$1}'
last -f  /var/log/btmp -20
echo ""
echo "\033[31m ### Checking bash history size ### \033[0m"
echo $HISTSIZE
echo "\033[31m ### Checking some special commands ### \033[0m"
history | grep -E 'wget|whoami|stunnel|mount'
echo "User history for special commands"
cat ~/.history | grep -E 'wget|whoami|stunnel|mount'
echo "\033[31m ### Checking bash history ### \033[0m"
history 100 | awk '{for(i=2;i<=NF;i++)printf"%s ",$i;printf" <-- "}'
echo "Checking user's bash history"
cat ~/.history 100 | awk '{for(i=2;i<=NF;i++)printf"%s ",$i;printf" <-- "}'
echo ""

echo "\033[31m ### Checking web logs ### \033[0m"
echo "\033[31m ### Checking presence of webshells ### \033[0m"
find / -type f -name '*.php' | xargs egrep '(phpspy|c99sh|include|milw0rm|eval\(gunerpress|eval\(base64_decode|spider_bc|@$)' | awk -F : '{print $1}' >> /tmp/checkweb.log
find / -type f -name "*.jsp" |xargs egrep 'exec|getRuntime()' >> /tmp/checkweb.log
find / -type f -name "*.asp*" |xargs egrep 'eval|execute|Request|VBScript'>> /tmp/checkweb.log
#grep -i 'select%20|sqlmap|script|phpinfo()|upload|cat' $LOGDIR/*log  | grep 500 | grep -i \.php >> /tmp/checkweb.log
find / -type f -name '*struts*'>> /tmp/checkweb.log
#cat /tmp/checkweb.log 
echo ""

echo "\033[31m ### Checking rootkits ### \033[0m"
rkhunter -c --sk > /tmp/rkhunter.log
grep 'Warning' /tmp/rkhunter.log
echo ""
echo "\033[31m ### Checking hidden programs/processes ### \033[0m"
nohup unhide sys >>/tmp/unhide.log
nohup unhide brute >>/tmp/unhide.log
nohup unhide proc >>/tmp/unhide.log
nohup unhide procall >>/tmp/unhide.log
nohup unhide procfs >>/tmp/unhide.log
nohup unhide quick >>/tmp/unhide.log
nohup unhide reverse >>/tmp/unhide.log
nohup unhide-tcp >>/tmp/unhide.log
#cat /tmp/unhide.log

echo '\033[31m ###checking backdoors ### \033[0m'
find / -name “.rhosts” -print 
find / -name “.forward” -print 

echo '\033[31m ###checking various log file sizes ### \033[0m'
if [ -f /etc/redhat-release ]; then
  ls -la -h /var/log/messages
  ls -la -h /var/log/maillog
  ls -la /var/log/mail/
fi

# Ref:
# * https://github.com/scopion/emergency-Response/blob/master/offline.sh
# * https://github.com/ffffffff0x/1earn/blob/master/1earn/Security/BlueTeam/%E5%8F%96%E8%AF%81.md
